import React from "react";

// Import type and fonts
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Import the Navbar component
import Navbar from "./navbar/navbar";

// Import global styles
import "./globals.css";

// Create a font instance
const inter = Inter({ subsets: ["latin"] });

// Define metadata
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Modify RootLayout to include the Navbar at the top
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* Include your head elements here */}</head>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
